# Gitpod configuration for AuraOS-Monorepo
image: gitpod/workspace-full

# Install dependencies and setup
tasks:
  - name: Setup AuraOS Landing Page
    init: |
      cd apps/landing-page
      npm install
      npm run build
    command: npm run dev

# Ports to expose
ports:
  - port: 4321
    onOpen: open-preview
    name: AuraAI Landing Page
  - port: 3000
    onOpen: open-preview
    name: SelfOS App

# VS Code extensions
vscode:
  extensions:
    - astro-build.astro-vscode
    - bradlc.vscode-tailwindcss
    - esbenp.prettier-vscode
    - ms-vscode.vscode-typescript-next
    - ms-vscode.vscode-json
    - ms-vscode.vscode-eslint

# Environment variables
env:
  - name: NODE_ENV
    value: development
  - name: PORT
    value: 4321