version: '3.8'

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: auraos-vllm
    ports:
      - "8000:8000"
    volumes:
      # Mount Hugging Face cache to persist downloaded models
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      # Model configuration
      - MODEL_NAME=meta-llama/Llama-3.1-8B-Instruct
      # Optional: Set Hugging Face token for gated models
      # - HUGGING_FACE_HUB_TOKEN=your_token_here
    command:
      - --model
      - meta-llama/Llama-3.1-8B-Instruct
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      # Enable tool/function calling support
      - --enable-auto-tool-choice
      - --tool-call-parser
      - hermes
      # Performance optimizations
      - --max-model-len
      - "8192"
      - --gpu-memory-utilization
      - "0.9"
      # Tensor parallelism (adjust based on your GPU count)
      # - --tensor-parallel-size
      # - "2"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  default:
    name: auraos-network
