name: Deploy to Firebase

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  build-and-deploy:
    name: Build and Deploy Desktop OS
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: packages/ui/package-lock.json

      - name: Install dependencies
        working-directory: packages/ui
        run: npm ci

      - name: Build Desktop OS
        working-directory: packages/ui
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Deployment Summary
        run: |
          echo "✅ Deployment successful!"
          echo "🌐 Desktop OS is now live"
          echo "📦 Build size: $(du -sh packages/ui/dist | cut -f1)"
